# Generated by Django 5.0.6 on 2024-07-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_bin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='hash_value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
