# Generated by Django 5.0.6 on 2024-07-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_bin', '0003_paste_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
