# Generated by Django 5.0.6 on 2024-07-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_bin', '0004_alter_paste_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='content',
            field=models.TextField(),
        ),
    ]
